- name: Job start
  hosts: all
#  serial: 1
  gather_facts: no
  tasks:
    - name: Assign date
      shell: "date +%m%d%Y"
      register: datetoday
      run_once: true

    - name: Create file
      file:
        dest: "/tmp/gpubsub-status{{ datetoday.stdout }}"
        state: touch
        mode: 0777
      run_once: true
      register : pbtmpfile
      delegate_to: localhost
#      become: False

    - name: Fetch Gpubsub status
      become: yes
      become_user: oracle
      shell: >
        echo "{{ hostvars[inventory_hostname].group_names[0] }} : {{ inventory_hostname }} :
        $(if [ -f "/opt/oracle/FMW12.2/soa/soa/connectors/google-pubsub-adapter-rar-0.3.2.rar" ]; then echo "Yes" ; else echo "No"; fi;)"
      register: op

    - name: Append output to onefile
      lineinfile:
        dest: "{{ pbtmpfile.dest}}"
        line: " {{ op.stdout }}"
        insertafter: EOF
      delegate_to: localhost
#      become: False

    - name: Send mail
      mail:
        host: localhost
        port: 25
        from: no.reply@IKEA.com
        to: "{{ maillist }}"
        subject: Google Pubsub Adapters status
        body: "{{ lookup('file', '{{ pbtmpfile.dest }}') }}"
      delegate_to: localhost
      run_once: true
#      become: False
    - name: Delete the file after mail
      file:
        path: "{{ pbtmpfile.dest }}"
        state: absent
      run_once: true
#      become: False
      delegate_to: localhost
