- name: Modifying the Coherence Config Listening Address & Unicast Address
  hosts: all
  gather_facts: no
  tasks:
    - name: Setting Weblogic Domain Home
      shell: pwdx `ps -ef | grep -i AdminServer | grep -v grep | awk '{print $2}'`| awk '{print $2}'
      register: Domain_Home
      when: servers is search('AdminServer')

    - debug:
        msg: "{{ Domain_Home.stdout_lines }}"
      when: servers is search('AdminServer')

    - name: Taking config backup
      shell: cp -pr {{ Domain_Home.stdout }}/config {{ Domain_Home.stdout }}/config_bkp_`date +%m%d%Y%H%M%S`
      when: servers is search('AdminServer')

    - name: Modifying the Unicast and Coherence listening address
      shell: |
        config={{ Domain_Home.stdout }}/config/config.xml
        coherence={{ Domain_Home.stdout }}/config/coherence/defaultCoherenceCluster-coherence.xml
        cp -pr ${config} ${config}_bkp_`date +%m%d%Y%H%M%S`
        cp -pr ${coherence} ${coherence}_bkp_`date +%m%d%Y%H%M%S`
        for i in `grep "unicast-listen-address" ${config}`
        do
        Name=$(echo $i | cut -d ">" -f2 | cut -d "<" -f1)
        Address=`nslookup $Name | grep -A1 Name | grep Address |awk '{print $NF}'`
        echo $Name
        echo $Address
        if [ -z $Address ]
        then
        echo "IP Address is Already there"
        else
        sed -i "s/$Name/$Address/g" ${coherence}
        sed -i "s/<unicast-listen-address>$Name/<unicast-listen-address>$Address/g" ${config}
        fi
        done
      register: output
      when: servers is search('AdminServer')

    - debug:
        msg: "{{ output.stdout_lines }}"
      when: servers is search('AdminServer')

   
