- name: Finding the Heap size
  hosts: all
  gather_facts: no
  vars_files:
  - ../group_vars/global.yml  
  
  tasks:
  - block:
    - shell: |
        echo -e "\n\n`hostname`"
        echo "========================"
        for i in `ps -ef | grep "Dweblogic.Name" | grep -v grep`
        do
          echo $i | grep Dweblogic.Name
          echo $i | grep Xms
          echo $i | grep Xmx
          echo $i | grep Ddomain.home | awk -F "/" '{print $1 $NF}'
          echo $i | grep weblogic.Server | sed 's/weblogic.Server//g'
        done
      register: Heap_output
      ignore_errors: yes


    - debug:
        msg: "{{ Heap_output.stdout_lines }}"

    - name: Assign date
      shell: "date +%m%d%Y%H%M%S"
      register: datetoday
      run_once: true

    - name: Collating output
      shell: echo -e " {{ Heap_output.stdout }} " >> "/tmp/Heap_output_{{ datetoday.stdout }}.txt"
      delegate_to: localhost
      become: false 

  
  - block:
    
    - name: Copy files to one of the servers
      copy:
        src: "/tmp/Heap_output_{{ datetoday.stdout }}.txt"
        dest: /tmp/

    - name: Collate files into the single file.
      shell: |
            echo "Plese find the heap size details for the given servers below" > /tmp/Heap_Final{{ datetoday.stdout }}
            cat "/tmp/Heap_output_{{ datetoday.stdout }}.txt" >> /tmp/Heap_Final{{ datetoday.stdout }}
            
    - name: Send the collated file as mail
      shell: "cat /tmp/Heap_Final{{ datetoday.stdout }} | mail -s Heap_Memory_Details -r {{ ansible_tower_mail_id }}@`hostname -d` {{ email_ids }}"

    - name: Delete the files from the remote server
      file:
        path: "/tmp/Heap_Final{{ datetoday.stdout }}"
        state: absent

    - name: Delete the files from the remote server
      file:
        path: "/tmp/Heap_output_{{ datetoday.stdout }}.txt"
        state: absent
 
    run_once: true

  - block:
    - name: Delete the files from Ansible server
      file:
        path: "/tmp/{{ inventory_hostname }}_Heap_Out_{{ datetoday.stdout }}.txt"
        state: absent
      become: false
      delegate_to: localhost
    run_once: true
     