- hosts: all
  gather_facts: no
  any_errors_fatal: true
  become: yes
  become_user: oracle

  vars_files:
  - ../group_vars/global.yml

  roles:
  - role: config-backup
    when: servers is search('Admin')

  - role: baseline
    patch_file: updateMuxerClassAndDisableLockout
    when: servers is search('Admin')

  - role: jdk-upgrade
    jdk_binary: jdk-8u212-linux-x64
    jdk_version: jdk1.8.0_212
    current_jdk_version: jdk1.8.0_144

- hosts: all
  gather_facts: no
  become: yes
  become_user: oracle

  vars_files:
  - ../group_vars/global.yml

  roles: 
  - role: blackout
    action: start
    tags: blackoutstart
    when: env not in ['PPE','PROD']

  - role: weblogic-restart
    action: stop
    tags: weblogicstop
    ignore_errors: yes
    when: env not in ['PPE','PROD']

  - role: weblogic-restart
    action: start
    tags: weblogicstart
    when: env not in ['PPE','PROD']

  - role: blackout
    action: stop
    tags: blackoutstop
    when: env not in ['PPE','PROD']
