- hosts: all
  gather_facts: no
  become: yes
  become_user: oracle

  vars_files:
  - ../group_vars/global.yml

  roles:
  - role: blackout
    action: start
    blackout_duration: 15

  - role: run-wlst
    patch_file: manage-ds
    when: servers is search('Admin')

  - role: blackout
    action: stop
