- hosts: "{{ hosts_list }}"
  gather_facts: no
  become: yes
  become_user: oracle

  vars_files:
  - ../group_vars/global.yml

  roles:
  - role: odi-wallet-entry
    when: stack == "odi" and servers is search('Admin') and fmw_version is version_compare('12.2','==')
