- name: ODI Wallet Password Encryption
  hosts: all
  gather_facts: no
  vars_files:
  - ../group_vars/global.yml 
  tasks:
  - block: 
    - name: Copy ODI Wallet Password Encryption Script
      copy:
        src: "../../wlst/miscelleneous/ODI_Wallet_Password_Encryption.py"
        dest: "/opt/oracle/scripts"
       
    - name: Execute Wallet Script
      shell: "python /opt/oracle/scripts/ODI_Wallet_Password_Encryption.py -m {{ Multi_entry }} -f {{ key_folder }}"
      register: Password_Encryption
      
 
    - debug:
        msg: "{{ Password_Encryption.stdout_lines }}"

    - name: Fetching Encrypted file to Localhost
      fetch:
        src: /oitp_odi/ODI_KEYS/Encrypted.txt
        dest: /tmp/Encrypted_{{ inventory_hostname }}.txt
        flat: yes

    when: servers is search('AdminServer')
    
  - block:
    - name: Collating output detials
      shell: |
         echo -e "\n\n Plese find the password encryption details for the given servers below \n\n"
         echo " {{ inventory_hostname }} "
         echo "========================="
         echo " {{ Password_Encryption.stdout }} "
      register: Mail_Output
      
    - name: Sending password encryption mail
      mail:
        host: localhost
        #port: 25
        from: ansible-tower@ikea.com
        to: vignesh.radhakrishnan@ingka.com, neelotpal.pandey@ingka.com 
        subject: ODI_Password_Encryption_{{ inventory_hostname }}
        attach: "/tmp/Encrypted_{{ inventory_hostname }}.txt"
        body: "{{ Mail_Output.stdout }}"
      delegate_to: localhost
      become: false  
    when: servers is search('AdminServer')        
    

  - block:
    - name: Delete the files from Ansible server
      file:
        path: "/tmp/Encrypted_{{ inventory_hostname }}.txt"
        state: absent
      become: false
      delegate_to: localhost
    






