- hosts: all
  gather_facts: no
  become: yes
  any_errors_fatal: true
  become_user: oracle

  vars_files:
  - ../group_vars/global.yml

  roles:
  - role: ../roles/generate-password
    run_once: true

  - role: ../roles/baseline
    patch_file: reset-weblogic-password
    additional_params: "{{ passwd.stdout }}"
    when: servers is search('Admin')

  - role: Update_Deployuser_pwd