- hosts: all
  gather_facts: no
  become: yes
  become_user: oracle
  #any_errors_fatal: true
  
  vars_files:
  - ../group_vars/global.yml
  
  roles:
  - role: config-backup
  
  - role: run-wlst
    patch_file: RJVM-Error-Fix
    when: servers is search('Admin')
 
  - role: ../roles/RJVM-Params