- hosts: all
  gather_facts: no
  #strategy: free
  become: yes
  become_user: oracle

  vars_files:
  - ../group_vars/global.yml

  roles:
  - role: config-backup
    when: servers is search('Admin')

  - role: run-wlst
    patch_file: server-identity-failed-fix
    when: servers is search('Admin')

