######################################################################################
#Date: 02-25-2020
#Prepared by: Praveen Kandregula(kakum7)
#Purpose: This is to validate tools status
######################################################################################
- hosts: ptseelm-lx41084.ikeadt.com
  gather_facts: no

  vars_files:   
  - ../group_vars/global.yml

  roles:
  - role: siti-tools-status 
    #delegate_to: localhost
