- hosts: all
  gather_facts: no
  become: yes
  become_user: oracle
  tasks:
  - name: Pick datasource names where soia db is used
    shell: "cd /opt/oracle/domains{{ fmw_version }}/{{ domains }}/config/jdbc && grep -i -r 'soia' . | awk '{print $1}' | uniq | awk -F'-' '{print $1}' | awk -F'/' '{print $2}'"
    register: dsnames

  - block:
    - name: Print results
      debug:
        msg: "{{ dsnames.stdout }}"

    - name: Check connectivity
      shell: "echo '{{ group_names }} - {{ inventory_hostname }}' && nc -vz itseelm-lx21076.ikea.com 6200 && nc -vz itseelm-lx21077.ikea.com 6200 && nc -vz itseelm-lx21078.ikea.com 6200 && nc -vz itseelm-lx21079.ikea.com 6200"
      register: op
      ignore_errors: yes

    - name: Print results
      debug:
        msg: "{{ op.stdout }} ==> {{ op.stderr }}"
    when: dsnames.stdout != ""


