- name: "Check if {{ value }} VIP is down"
  shell: |
          sudo wlipctl status ip -a | grep inactive | egrep '{{ key }}' | awk '{print $1}' | awk -F':' '{print $2}' | sed 's/]//g'
  when: servers is search(value) and action == "start"
  register: vipstatus

#- name: "Check if {{ value }} VIP is up"
#  shell: |
#          sudo wlipctl status ip -a | grep 'is active' | egrep '{{ key }}' | awk '{print $1}' | awk -F':' '{print $2}' | sed 's/]//g'
#  when: servers is search(value) and action == "stop"
#  register: vipstatus
  
- name: "{{ action }} {{ value }} VIPs"
  shell: |
          sudo wlipctl {{ action }} ip -i {{ vip }}
  with_items:
  - "{{ vipstatus.stdout_lines }}"
  when: vipstatus.stdout is defined and vipstatus.stdout != ""
  loop_control:
    loop_var: vip
