- name: "Validate if domains backup available with {{ dt_suffix.stdout }}"
  stat:
    path: "/opt/oracle/domains{{ fmw_version }}-{{ dt_suffix.stdout }}"
  register: backup_status

- block:
  - name: Create backup directory it it doesn't exist
    file:
      path: "/opt/oracle/domains{{ fmw_version }}-{{ dt_suffix.stdout }}"
      state: directory

  - name: Backup domains folder
    copy:
      src: "/opt/oracle/domains{{ fmw_version }}"
      dest: "/opt/oracle/domains{{ fmw_version }}-{{ dt_suffix.stdout }}/"
      remote_src: yes
  
  #- name: Backup domains folder
  #  synchronize:
  #    src: "/opt/oracle/domains{{ fmw_version }}/"
  #    dest: "/opt/oracle/domains{{ fmw_version }}-{{ dt_suffix.stdout }}"
  #    rsync_opts:
  #    - "--exclude=*.log*"
  #    - "--exclude=*.out*"
  #    - "--exclude=*.hprof*"
  #    - "--exclude=*erver*/tmp/*"
  #    - "--exclude=*erver*/cache/*"
  #    - "--exclude=*bsu/cache_dir/*"
  #    - "--exclude=*/adr/*"
  #  delegate_to: "{{ inventory_hostname }}"
  when: backup_status.stat.exists == false
