- name: Ensure /opt/oracle/scripts exists and clean
  file:
    path: /opt/oracle/scripts
    state: "{{ item }}"
  with_items:
  - "absent"
  - "directory"

- name: Pick date
  shell: "date +'%m%d%Y'"
  register: dt_suffix
  #run_once: true

- include: backup.yml

- include: generate-password.yml
  #run_once: true
