- set_fact:
    job_url: "https://tower.ikea.com/#/jobs/playbook/{{ hostvars[inventory_hostname]['tower_job_id'] }}"
    #wallet_entry_email_ids: 'kakum7@ikea.com'

- set_fact:
    scripts_home: "/opt/oracle/scripts"

- name: Create scripts home
  file: 
    state: directory
    path: " {{ scripts_home }}"

- name: Copy scripts
  copy: 
    src: "{{ item }}"
    dest: "{{ scripts_home }}"
  with_items:
  - "../../../../apps/odi-wallet-entry/wallet-entry.py"

- name: Copy properties
  copy: 
    src: "{{ item }}"
    dest: "{{ scripts_home }}/.wallet.properties"
  with_items:
  - "../../../../apps/odi-wallet-entry/wallet.properties"
  no_log: true

- name: Collect mkkstore path
  shell: "find /opt/oracle/FMW12.2 -type f -name mkstore"
  register: mkpath

- name: Run script
  #shell: "source /opt/oracle/domains12.2/{{ item }}/bin/setDomainEnv.sh && python {{ scripts_home }}/wallet-entry.py -a {{ action }} -x {{ dbs }} -s '{{ conn_string }}' -m {{ vars[env + '_mkstore_path'] }} -d {{ item }} > {{ scripts_home }}/odi-wallet-entry-output.txt"
  shell: "source /opt/oracle/domains12.2/{{ item }}/bin/setDomainEnv.sh && python {{ scripts_home }}/wallet-entry.py -a {{ action }} -x {{ dbs }} -s '{{ conn_string }}' -m {{ mkpath.stdout }} -d {{ item }} > {{ scripts_home }}/odi-wallet-entry-output.txt"
  register: op
  with_items:
  - "{{ domains.split(',') }}"
  ignore_errors: true

- name: Housekeeping   
  file:     
    path: "{{ scripts_home }}/{{ item }}"     
    state: absent   
  with_items:   
  - ".wallet.properties"   
  #- "odi-wallet-entry-output.txt"

- debug:
    msg: "{{ op }}"

- name: Send details over email with SUCCESS status
  shell: "echo 'Please find the attached output' | mail -s 'SUCCESS!!!'`hostname -f`'-ODI wallet entry status' -a {{ scripts_home }}/odi-wallet-entry-output.txt -r ansible-tower@`hostname -d` {{ wallet_entry_email_ids }}"
  when: item.rc|int == 0
  with_items:
  - "{{ op.results }}"

- name: Send details over email with FAILURE status
  shell: "echo -e 'Execution has failed!!!\nExecuted by: {{ hostvars[inventory_hostname]['awx_user_name'] }}\nPlease review the log at {{ job_url }}' | mail -s 'FAILURE!!!'`hostname -f`'-ODI wallet entry status' -r ansible-tower@`hostname -d` {{ wallet_entry_email_ids }} && exit 1"
  #when: op.stderr is defined and "'Execution failed' in op.stdout"
  #when: op.failed
  when: item.rc|int != 0
  with_items:
  - "{{ op.results }}"

