- name: Create backup directory
  file:
    path: "{{ folder_name }}-{{ dt_suffix.stdout }}"
    state: directory

- name: "Backup appagent and machineagent folders"
  copy:
    src: "/opt/appdynamics/{{ folder_name }}/"
    dest: "/opt/appdynamics/{{ folder_name }}-{{ dt_suffix.stdout }}"
    remote_src: yes
    directory_mode: yes

- name: "Remove old files of AppAgent and machineagent"
  file:
    path: "/opt/appdynamics/{{ folder_name }}"
    state: "{{ item1 }}"
  with_items:
  - "absent"
  - "directory"
  loop_control:
    loop_var: item1
