- name: Pick date
  shell: "date +'%d%m%Y-%H%M%S'"
  register: dt_suffix
  run_once: true
  
- set_fact:
    scripts_home: "/opt/oracle/scripts"
    binaries_home: "/opt/oracle/binaries"
    appagent_binary: "AppServerAgent-4.5.10.25916"
    machineagent_binary: "MachineAgent-4.5.11.2163"
    agents: "appagent,machineagent"

- set_fact:
    agent_versions: "{{ appagent_binary }},{{ machineagent_binary }}"
    appagent_version: "{{ appagent_binary.split('-')[1] }}"
    machineagent_version: "{{ machineagent_binary.split('-')[1] }}"
  
- name: Create directory to place binaries
  file:
    path: "{{ binaries_home }}"
    state: directory
    
- include: copy-binaries.yml binary_name="{{ item }}"
  with_items: 
  - "{{ appagent_binary }}"
  - "{{ machineagent_binary }}"

- include: backup-and-cleanup.yml folder_name="{{ item }}"
  with_items:
  - "appagent"
  - "machineagent"

- name: Unzip appagent and machineagent
  unarchive:
    src: "{{ binaries_home }}/{{ item.1 }}.zip" 
    dest: "/opt/appdynamics/{{ item.0 }}/"
    remote_src: yes
  with_together:
  - "{{ agents.split(',') }}"
  - "{{ agent_versions.split(',') }}"

#- name: Copy unzipped files from AGENT_NEW to agent_home
#  copy: 
#    src: "/opt/appdynamics/{{ item }}/{{ item }}_NEW/ver{{ vars[item + '_version'] }}/"
#    dest: "/opt/appdynamics/{{ item }}/"
#    remote_src: true
#  with_items:
#  - "appagent"
#  - "machineagent"

- name: Backup config files
  copy:
    src: "{{ item }}"
    dest: "{{ item }}-{{ dt_suffix.stdout }}"
    remote_src: true
  with_items:
  - "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
  - "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/app-agent-config.xml"
  - "/opt/appdynamics/machineagent/conf/controller-info.xml"
  - "/opt/appdynamics/machineagent/monitors/analytics-agent/conf/analytics-agent.properties"

#- name: Insert/Update HTML surrounded by custom markers after <body> line
#  blockinfile:
#    path: "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/app-agent-config.xml"
#    block: |20
#            <!-- exclude this package from getting instrumented specifically for the async Comment by Surendra GINT -->
#            <excludes filter-type="STARTSWITH" filter-value="com/octetstring/"/>
#            <excludes filter-type="STARTSWITH" filter-value="com/tangosol/"/>"
#    insertbefore: "                    <!-- exclude java and org -->"
#    backup: yes
#  tags: config
- name: Copy app-agent-config.xml template
  template:
    src: app-agent-config.xml.j2
    dest: "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/app-agent-config.xml"
 
- name: Update controller-info.xml of appagent and machineagent
  replace:
    path: "{{ item[0] }}" 
    regexp: "{{ item[1].split(':')[0] }}"
    replace: "{{ item[1].split(':')[1] }}"
  with_nested:
  - '["/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml", "/opt/appdynamics/machineagent/conf/controller-info.xml"]'
  - '["<controller-host></controller-host>:<controller-host>{{ vars[env + "_controller_host"] }}</controller-host>", "<controller-port></controller-port>:<controller-port>{{ vars[env + "_controller_port"] }}</controller-port>", "<controller-ssl-enabled></controller-ssl-enabled>:<controller-ssl-enabled>true</controller-ssl-enabled>", "<account-name></account-name>:<account-name>{{ vars[env + "_controller_account"] }}</account-name>", "<account-access-key></account-access-key>:<account-access-key>{{ vars[env + "_new_key"] }}</account-access-key>"]'

#- name: Update APPD host and port in appagent and machineagent configs
#  replace:
#    path: "{{ item }}"
#    regexp: '<controller-host></controller-host>'
#    replace: '<controller-host>{{ vars[env + "_controller_host"] }}</controller-host>'
#  with_items:
#  - "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
#  - "/opt/appdynamics/machineagent/conf/controller-info.xml"
#- replace:
#    path: "{{ item }}"
#    regexp: '<controller-port></controller-port>'
#    replace: '<controller-port>{{ vars[env + "_controller_port"] }}</controller-port>'
#  with_items:
#  - "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
#  - "/opt/appdynamics/machineagent/conf/controller-info.xml"

#- name: Update the controller-SSL Value in App Agent
#  replace:
#    path: "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
#    regexp: '<controller-ssl-enabled></controller-ssl-enabled>'
#    replace: '<controller-ssl-enabled>true</controller-ssl-enabled>'

#- name: Updating the Account Name Value in App and Machine Agent
#  replace:
#    path: "{{ item }}"
#    regexp: '<account-name></account-name>'
#    replace: '<account-name>{{ vars[env + "_controller_account"] }}</account-name>'
#  with_items:
#  - "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
#  - "/opt/appdynamics/machineagent/conf/controller-info.xml"

#- name: Updating the Access Key Value in App Agent
#  replace:
#    path: "{{ item }}"
#    regexp: '<account-access-key></account-access-key>'
#    replace: '<account-access-key>{{ vars[env + "_new_key"] }}</account-access-key>'
#  with_items:
#  - "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
#  - "/opt/appdynamics/machineagent/conf/controller-info.xml"
- name: Update machineagent's controller-info.xml
  replace:
    path: "/opt/appdynamics/machineagent/conf/controller-info.xml"
    regexp: "{{ item.split(':')[0] }}"
    replace: "{{ item.split(':')[1] }}"
  with_items:
  - "<controller-ssl-enabled>false</controller-ssl-enabled>:<controller-ssl-enabled>true</controller-ssl-enabled>"
  - "<unique-host-id></unique-host-id>:<unique-host-id>{{ inventory_hostname }}</unique-host-id>"
  - "<sim-enabled>false</sim-enabled>:<sim-enabled>true</sim-enabled>"

- name: Update machineagent's analytics-agent.properties
  replace:
    path: "/opt/appdynamics/machineagent/monitors/analytics-agent/conf/analytics-agent.properties"
    regexp: "{{ item.split(':')[0] }}"
    replace: "{{ item.split(':')[1] }}"
  with_items:
  - "ad.agent.name=analytics-agent1:ad.agent.name={{ inventory_hostname }}"
  - "appdynamics.agent.uniqueHostId=:appdynamics.agent.uniqueHostId={{ inventory_hostname }}"
  - "http.event.name=customer1:http.event.name={{ vars[env + '_controller_account'] }}"
  - "http.event.accountName=analytics-customer1:http.event.accountName={{ vars[env + '_controller_account'] }}_1fef18c0-fc03-4782-a34a-3f05bd912858"
  - "http.event.accessKey=your-account-access-key:http.event.accessKey={{ vars[env + '_new_key'] }}"
 
- name: Update hostnames in machineagent configuration
  replace:
    path: "/opt/appdynamics/machineagent/monitors/analytics-agent/conf/analytics-agent.properties"
    regexp: "{{ item.split('$')[0] }}"
    replace: "{{ item.split('$')[1] }}"
  with_items:
  - "ad.controller.url=http://localhost:8090$ad.controller.url=https://{{ vars[env + '_controller_host'] }}:{{ vars[env + '_controller_port'] }}"
  - "http.event.endpoint=http://localhost:9080$http.event.endpoint=https://fra-ana-api.saas.appdynamics.com:443"

- name:  Add keystore information to controller-info.xml
  lineinfile:
    path: "/opt/appdynamics/appagent/ver{{ appagent_version }}/conf/controller-info.xml"
    line: "{{ item }}"
    insertbefore: "</controller-info>"
  with_items:
  - "    <!--Certificate Installation configuration for AppDynamics Comment by Surendra GINT-->"
  - "    <controller-keystore-password>{{ vars[env + '_cacerts_password'] }}</controller-keystore-password>"
  - "    <controller-keystore-filename>./cacerts.jks</controller-keystore-filename>"

- name: Update keys in config_machineagent.sh
  replace:
    path: "/opt/appdynamics/machineagent/config_machineagent.sh"
    regexp: "{{ item.split(':')[0] }}"
    replace: "{{ item.split(':')[1] }}"
  with_items:
  - "{{ PPE_old_key }}:{{ PPE_new_key }}"
  - "{{ PROD_old_key }}:{{ PROD_new_key }}"
  
- name: Run configure
  shell: "cd /opt/appdynamics/machineagent && /opt/appdynamics/machineagent/config_machineagent.sh -e {{ vars[env + '_controller_account'] }} -a {{ vars[env + '_new_key'] }}"
  
- name: Create scripts_home directory
  file:
    path: "{{ scripts_home }}"
    state: directory
  
- name: Copy machineagent restart script
  copy:
    src: "../../../../shell-scripts/restart-appd-machineagent.sh"
    dest: "{{ scripts_home }}"
    
- name: Restart machine agent
  shell: " sh {{ scripts_home }}/restart-appd-machineagent.sh"
