- name: Create tempfile
  tempfile:
    state: file
    path: /tmp
    prefix: current-patches-output
  register: outputFile
  run_once: true

- name: set fact opatch_home for 12C
  set_fact: 
    opatch_home: "/opt/oracle/FMW{{ fmw_version }}/OPatch"
  when: fmw_version is version_compare('12.2','==')

- name: set fact opatch_home for 11G
  set_fact:
    opatch_home: "/opt/oracle/FMW{{ fmw_version }}/oracle_common/OPatch"
  when: opatch_home is undefined and fmw_version is version_compare('12.2','!=')

- name: Listdown current patches
  shell: "{{ opatch_home }}/opatch lsinventory | grep -i applied | awk '{print $2}' | sort | paste -s -d, - >> {{ outputFile.path }}"

- name: "Change permissions of {{ outputFile.path }}"
  file: 
    path: "{{ outputFile.path }}"
    state: file
    mode: 0777

