- shell: "cat {{ outputFile.path }}"
  register: op
  when: fmw_version is version_compare('12.2','!=')

- name: Collate results to localhost
  shell: "echo {{ stack }} : {{ inventory_hostname }}: {{ item }} >> {{ outputFile.path }}"
  with_items:
  - "{{ op.stdout_lines }}"
  when: fmw_version is version_compare('12.2','!=')
  delegate_to: localhost

- name: Remove tempfile
  file:
    path: "{{ outputFile.path }}"
    state: absent
  when: fmw_version is version_compare('12.2','!=')
  become: yes
  become_user: oracle

- block:
  - name: Pick date
    shell: "date +'%D'"
    register: dt

  - name: Copy collated results from Ansible server to one of the servers
    copy:
      src: "{{ outputFile.path }}"
      dest: /tmp/
  
  - name: Send results over email
    shell: "cat {{ outputFile.path }} | sort | mail -s {{ env }}-bsu-current-patches-{{ dt.stdout }} -r {{ ansible_tower_mail_id }}@`hostname -d` {{ email_ids }}"
  run_once: true

- name: Remove tempfile on ansible server
  file:
    path: "{{ outputFile.path }}"
    state: absent
  run_once: true
  delegate_to: localhost
