- stat:
    path: /oitp_soa
  register: oitp_soa
  tags: 
    - copyscripts
    - binaries

- stat:
    path: /oitp_osb
  register: oitp_osb
  tags:
    - copyscripts
    - binaries

- name: Pick date
  shell: "date +'%m%d%Y'"
  register: dt_suffix
  run_once: true

- debug:
    var: dt_suffix.stdout
# Backup of /oraInventory
- name: Back up of OraInventory
  copy:
    src: "/u01/app/oraInventory"
    dest: "/u01/app/oraInventory_BKP_{{dt_suffix.stdout}}"
    remote_src: yes
    directory_mode: yes

- name: "Check if domain-registry.xml exists"
  stat:
    path: "{{ ORACLE_HOME }}/domain-registry.xml"
  register: domRegExists

- name: "extract domain dirs"
  set_fact:
    domains: []

- name: "Backup domains"
  block:
  - name: Slurp hosts file
    slurp:
      src: "{{ ORACLE_HOME }}/domain-registry.xml"
    register: dom_reg

  - name: "extract domain dirs"
    set_fact:
      domains: '{{ dom_reg["content"] | b64decode | get_domains  }}'
      backuptime: "{{ '%Y%m%d%H%M%S' | strftime }}"

  - name: "Backup domains"
    archive:
       path: "{{ domain }}"
       dest: "{{ domain }}.bkp{{backuptime}}.tar.gz"
    loop: "{{ domains }}"
    loop_control:
      loop_var: domain
    when: domRegExists.stat.exists

  - name: "Check Oracle home is not empty"
    find:
      paths: "{{ ORACLE_HOME }}"
    register: filesFound

  - name: "Backup oracle home"
# /opt/oracle/domains12.2/PTOWD3642.bkp1222222.tar.gz"
    archive:
      path: "{{ ORACLE_HOME }}"
      dest: "{{ ORACLE_HOME | dirname}}/{{ ORACLE_HOME | basename}}.bkp{{backuptime}}.tar.gz"
    when: filesFound.matched > 0

#when: backup_status.stat.exists == false
# Creating a folder to Copy the Binary,
- block:
  - name: Create directory to place patches
    file:
      state: directory
      path: "{{item}}"
      owner: oracle
      group: oinstall
      mode: 0777
    with_items:
     - "/oitp_soa/12214"
    when: 
      - servers is search('Admin')
      - oitp_soa.stat.exists == True
    tags: binaries
# Fetching Patches to Local Servers,
  - name: Fetch patches to local server
    get_url:
      url: https://satellite.ikea.com/pub/OIP/OITP/V3/12214/{{ item }}
      tmp_dest: /oitp_soa/
      dest: /oitp_soa/12214
      #    run_once: true
    with_items:
      - fmw_12.2.1.4.0_infrastructure.jar
      - fmw_12.2.1.4.0_soa.jar
      - jdk-8u231-linux-x64.tar.gz
      - linuxx64_12201_client.zip
# Extracting Patch to the Location,
  #- name: "Extract the Binary file into Target Share Mount Point"
   # unarchive:
    #     src: /oitp_soa/12214/12214.tar
     #    dest: /oitp_soa/12214
      #   tmp_dest: /oitp_soa/
       #  remote_src: yes
        # owner: oracle
         #group: oinstall
    when: 
      - servers is search('Admin')
      - oitp_soa.stat.exists == True
    tags: binaries
  # Creating a folder to Copy the Binary,

- block:
  - name: Create directory to place patches
    file:
      state: directory
      path: "{{item}}"
      owner: oracle
      group: oinstall
      mode: 0777
    with_items:
     - "/oitp_osb/12214"
    when: 
      - servers is search('Admin')
      - oitp_osb.stat.exists == True
    tags: binaries
# Fetching Patches to Local Servers from satellite,
  - name: Fetch patches to local server
    get_url:
      url: https://satellite.ikea.com/pub/OIP/OITP/V3/12214/{{ item }}
      tmp_dest: /oitp_osb
      dest: /oitp_osb/12214
      #    run_once: true	  
    with_items:
      - fmw_12.2.1.4.0_infrastructure.jar
      - fmw_12.2.1.4.0_osb.jar
      - jdk-8u231-linux-x64.tar.gz
      - linuxx64_12201_client.zip
# Extracting Patch to the Location,
 # - name: "Extract the Binary file into Target Share Mount Point"
  #  unarchive:
   #      src: /oitp_osb/12214/12214.tar
    #     dest: /oitp_osb/12214
     #    remote_src: yes
      #   owner: oracle
       #  group: oinstall
    when:
      - servers is search('Admin')
      - oitp_osb.stat.exists == True
    tags: binaries

- block:  
  - name: Get script files to local server
    fetch:
      src: "/opt/repo/fmwscripts/fmw1214upgradescr.zip"
      dest: /tmp/
      flat: yes
    delegate_to: ptseelm-lx4253.ikeadt.com
    when: servers is search('Admin')
#    run_once: true
    tags: copyscripts

  - name: Copy scripts to osb servers
    copy:
      src: "/tmp/fmw1214upgradescr.zip"
      dest: "/oitp_osb/"
    when:
      - servers is search('Admin')
      - oitp_osb.stat.exists == True
    tags: copyscripts

  - name: Copy scripts to soa servers
    copy:
      src: "/tmp/fmw1214upgradescr.zip"
      dest: "/oitp_soa/"
    when:
      - servers is search('Admin')
      - oitp_soa.stat.exists == True
    tags: copyscripts
