- name: Copy reset-weblogic-password.py
  copy:
    src: ../../../../wlst/miscelleneous/reset-weblogic-password.py
    dest: /opt/oracle/scripts/

- include: 12c-extract.yml
  when: fmw_version is version_compare('12.2','==')

- include: 11g-extract.yml
  when: fmw_version is version_compare('12.2','!=')

#- name: Debug AdminHost and AdminPort
#  debug:
#    msg: "{{ item1 }}"
#  with_items: 
#  - "AdminHost: {{ admhost }}"
#  - "AdminPort: {{ admport }}"
#  loop_control:
#    loop_var: item1
#  when: admhost is defined and admport is defined

- name: Execute script
  shell: "source /opt/oracle/domains{{ fmw_version }}/{{ item }}/servers/AdminServer/security/boot.properties && /opt/oracle/FMW{{ fmw_version }}/oracle_common/common/bin/wlst.sh /opt/oracle/scripts/reset-weblogic-password.py $password {{ item }} {{ fmw_version }} {{ adminhost.stdout }} {{ adminport.stdout }} {{ passwd.stdout }}"
  #when: admhost is defined and admport is defined
  with_items:
  - "{{ domains.split(',') }}"
  register: scriptop
  failed_when: '"Script execution failed" in scriptop.stdout'
