- name: Update boot.properties under domain home with new password
  lineinfile:
    path: "/opt/oracle/domains{{ fmw_version }}/{{ item }}/boot.properties"
    regexp: "^password="
    line: "password={{ passwd.stdout }}"
    backup: yes
    state: present
  with_items:
  - "{{ domains.split(',') }}"

#- name: Update server specific boot.properties with new password
#  lineinfile:
#    path: "/opt/oracle/domains{{ fmw_version }}/{{ item[0] }}/servers/{{ item[1] }}/security/boot.properties"
#    regexp: "^password="
#    line: "password={{ passwd.stdout }}"
#    backup: yes
#    state: present
#  with_nested:
#  - "{{ domains.split(',') }}"
#  - "{{ servers.split(',') }}"
  
- name: Update nodemanager boot.properties with new password
  lineinfile:
    path: "/opt/oracle/domains{{ fmw_version }}/{{ item[0] }}/servers/{{ item[1] }}/data/nodemanager/boot.properties"
    regexp: "^password="
    line: "password={{ passwd.stdout }}"
    backup: yes
    state: present
  with_nested:
  - "{{ domains.split(',') }}"
  - "{{ servers.split(',') }}"
