- name: "{{ inventory_hostname }} - Pick date"
  shell: "date +'%m%d%Y-%H%M%S'"
  register: dt_suffix
  #run_once: true

- name: "{{ inventory_hostname }} - Create backup directory"
  file:
    path: "/opt/oracle/domains{{ fmw_version }}/{{ item }}/config-{{ dt_suffix.stdout }}"
    state: directory
  with_items:
  - "{{ domains.split(',') }}"

#- name: Backup config folder
#  synchronize:
#    src: "/opt/oracle/domains{{ fmw_version }}/{{ item }}/config/"
#    dest: "/opt/oracle/domains{{ fmw_version }}/{{ item }}/config-{{ dt_suffix.stdout }}/"
#    recursive: yes
#  with_items:
#  - "{{ domains.split(',') }}"
#  delegate_to: "{{ inventory_hostname }}"

- name: "{{ inventory_hostname }} - Backup config fodler"
  copy:
    src: "/opt/oracle/domains{{ fmw_version }}/{{ item }}/config/"
    dest: "/opt/oracle/domains{{ fmw_version }}/{{ item }}/config-{{ dt_suffix.stdout }}/"
    remote_src: yes
    directory_mode: yes
  with_items:
  - "{{ domains.split(',') }}"
  delegate_to: "{{ inventory_hostname }}"

