- shell: "cat /tmp/health-check-output.out"
  register: op

- name: Collate results to localhost
  shell: |
          echo "{{ inventory_hostname }}:" && echo "----------------------------------" && printf "\n" && echo {{ op.stdout }} && echo "----------------------------------" >> /tmp/health-check-output.out
  delegate_to: localhost

- block:
  - name: Copy collated results from Ansible server to one of the servers
    copy:
      src: "/tmp/health-check-output.out"
      dest: "/tmp/"
  
  - name: Send results over email
    shell: "cat /tmp/health-check-output.out | sort | mail -s {{ env }}-Health-check-report-{{ dt.stdout }} -r {{ ansible_tower_mail_id }}@`hostname -d` kakum7@ikea.com"
  run_once: true

- name: Remove output file on ansible server
  file:
    path: "/tmp/health-check-output.out"
    state: absent
  run_once: true
  delegate_to: localhost
