- name: List down all variables
  debug:
    msg: "{{ item }}"
  with_items:
  - "{{ domains }}"
  - "{{ servers }}"
  - "{{ fmw_version }}"
  - "{{ stack }}"

- name: "Check if {{ servers }} are running"
  shell: "ps -ef | grep -i {{ item }}"
  with_items: 
  - "{{ servers.split(',') }}"

- name: "Check if {{ domains }} exist"
  stat:
    path: "/opt/oracle/domains{{ fmw_version }}/{{ item }}"
  with_items:
  - "{{ domains }}"
  register: domainpathvalidation
  failed_when: domainpathvalidation.stat.exists != true

