#- name: Write msg to output file
#  shell: "echo {{ msg }} > /tmp/health-check-output.out"
#  when: msg is defined

- include: 12c-extract.yml
  when: fmw_version is version_compare('12.2','==')

- include: 11g-extract.yml
  when: fmw_version is version_compare('12.2','!=')

- name: Debug AdminHost and AdminPort
  debug:
    msg: "{{ item }}"
  with_items: 
  - " {{ adminhost | map(attribute='stdout') | list }}"
  - " {{ adminport | map(attribute='stdout') | list }}"
  when: admhost is defined and admport is defined

- name: Create directory to place scripts
  file:
    state: directory
    path: /opt/oracle/scripts

- name: Copy credentials
  copy:
    src: "../../../../wlst/credentials.properties"
    dest: "/opt/oracle/scripts/.credentials.properties"
  no_log: true

- name: Copy wlst scripts
  copy:
    src: "{{ item }}"
    dest: "/opt/oracle/scripts/"
  with_items:
  - "../../../../wlst/commons.py"
  - "../../../../wlst/miscelleneous/healthCheck.py"

- name: Execute script
  shell: "> /tmp/health-check-output.out && cd /opt/oracle/scripts && /opt/oracle/FMW{{ fmw_version }}/oracle_common/common/bin/wlst.sh healthCheck.py {{ adminhost.stdout }} {{ adminport.stdout }}"
  ignore_errors: yes

- name: Send results over email
  shell: "cat /tmp/health-check-output.out | mail -s {{ env }}-{{ inventory_hostname }}-{{ domain_name }}-health-check -r {{ ansible_tower_mail_id }}@`hostname -d` {{ email_ids }}"
