- name: "validate {{ endpoint }} status"
  uri:
    url: "{{ endpoint }}"
    status_code: 200,403
    timeout: 30
    validate_certs: no
  register: op
  ignore_errors: yes
  delegate_to: "{{ delegate }}"

- name: Write status to tempfile
  shell: |
          echo {{ endpoint }},{{ op.status }} >> {{ outputFile.path }}
