- name: Pick date
  shell: "date +'%d%m%Y-%H%M%S'"
  register: dt

- name: Create /opt/oracle/scripts to place scripts
  file:
    path: "/opt/oracle/scripts"
    state: directory

- name: Copy 
  copy:
    src: "../../../../lip-sapp/prepare-ms-name.sh"
    dest: "/opt/oracle/scripts"

- name: Shutdown
  include: shutdown.yml stack="{{ item }}"
  with_items:
  - "sapp"
  - "lip"
  when: activity == "stop"

- name: Startup
  include: startup.yml stack="{{ item }}"
  with_items:
  - "sapp"
  - "lip"
  when: activity == "start"

- name: Delete /opt/oracle/scripts
  file:
    path: "/opt/oracle/scripts"
    state: absent
