- name: Create tempfile
  tempfile:
    state: file
    path: /tmp
    prefix: tmp
  register: outputFile
  run_once: true
  delegate_to: localhost

- name: Print domain hostname combinations
  shell: "echo {{ item }}:{{ inventory_hostname }}:{{ servers }}:{{ fmw_version }} >> {{ outputFile.path }}"
  with_items:
  - "{{ domains.split(',') }}"
  delegate_to: localhost

- block:
  - name: Copy temp file to one of the servers
    copy:
      src: "{{ outputFile.path }}"
      dest: "{{ outputFile.path }}"

  - name: Copy script
    copy:
      src: "{{ item }}"
      dest: "/tmp"
    with_items:
    - "../../../../apps/groupSimplify.py"

  - name: Run python script
    shell: "python /tmp/groupSimplify.py {{ outputFile.path }}"
    register: combos

  - name: Copy secrets to server
    copy:
      src: "{{ item }}"
      dest: "/home/oracle/.credentials.properties"
    with_items:
    - "../../../../wlst/credentials.properties"

  - block:
    - name: Trigger Jenkins job for 12C domains in PTE/CTE environments
      shell: |
              source /home/oracle/.credentials.properties && curl -X POST "https://$pte_jenkins_user:$pte_jenkins_user_token@pte-iiptools.ikeadt.com/jenkins/job/Operations.Infrastructure/job/Certificate.List/buildWithParameters?DOMAIN_NAME={{ item.key }}&SERVER_LIST={{ item.value['hosts'] }}&ENV_TYPE={{ item.value['stack'] }}&&KEYSTORE_PASS=$keystore_password_12c&&JAVASTORE_PASS=$cacerts_password&&Recipients={{ jenkins_gint_infra_recepients }}&&NO_OF_DAYS=45&&STORELIST=Identity%20Trust%20AND%20Java%20Store" && sleep 10
      with_dict:
      - "{{ combos.stdout }}"
      when: env in ['PTE','CTE']

    - name: Trigger Jenkins job for 12C domains in PPE environment
      shell: |
              source /home/oracle/.credentials.properties && curl -X POST "https://$ppe_jenkins_user:$ppe_jenkins_user_token@ppe-iiptools.ikeadt.com/jenkins/job/Operations.Infrastructure/job/Certificate.List/buildWithParameters?DOMAIN_NAME={{ item.key }}&SERVER_LIST={{ item.value['hosts'] }}&ENV_TYPE={{ item.value['stack'] }}&&KEYSTORE_PASS=$keystore_password_12c&&JAVASTORE_PASS=$cacerts_password&&Recipients={{ jenkins_gint_infra_recepients }}&&NO_OF_DAYS=45&&STORELIST=Identity%20Trust%20AND%20Java%20Store" && sleep 10
      with_dict:
      - "{{ combos.stdout }}"
      when: env == 'PPE'

    - name: Trigger Jenkins job for 12C domains in PROD environment
      shell: |
              source /home/oracle/.credentials.properties && curl -X POST "https://$prod_jenkins_user:$prod_jenkins_user_token@prod-iiptools.ikea.com/jenkins/job/Operations.Infrastructure/job/Certificate.List/buildWithParameters?DOMAIN_NAME={{ item.key }}&SERVER_LIST={{ item.value['hosts'] }}&ENV_TYPE={{ item.value['stack'] }}&&KEYSTORE_PASS=$keystore_password_12c&&JAVASTORE_PASS=$cacerts_password&&Recipients={{ jenkins_gint_infra_recepients }}&&NO_OF_DAYS=45&&STORELIST=Identity%20Trust%20AND%20Java%20Store" && sleep 10
      with_dict:
      - "{{ combos.stdout }}"
      when: env == 'PROD'
    when: item.value['version'] is version_compare('12.2','==')

  - name: Remove credentials
    file:
      path: /home/oracle/.credentials.properties
      state: absent
  run_once: true
  become: yes
  become_user: oracle
          
- name: Remove tempfile
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ outputFile.path }}"
  - " /tmp/.credentials.properties"
  delegate_to: localhost
  run_once: true
