- name: Pick date
  shell: "date +'%m%d%Y-%H%M%S'"
  register: dt_suffix

- name: Fetch jdk from build server to Ansible Tower
  fetch: 
    src: "/opt/repo/jdk/{{ jdk_binary }}.tar"
    dest: /tmp/
    flat: yes
  delegate_to: ptseelm-lx4253.ikeadt.com
  run_once: true

#- name: Copy jdk to servers
#  copy: 
#    src: "/tmp/{{ jdk_version }}.tar"
#    dest: "/opt/oracle/"

#- name: Crete jdk cirectory
#  file:
#    path: "/opt/oracle/{{ jdk_version }}"
#    state: directory

- name: Unarchive jdk tar to target servers
  unarchive: 
    src: "/tmp/{{ jdk_binary }}.tar"
    dest: "/opt/oracle/"
    mode: '0755'

- name: "Backup cacerts of {{ jdk_version }}"
  copy:
    src: "/opt/oracle/{{ jdk_version }}/jre/lib/security/cacerts"
    dest: "/opt/oracle/{{ jdk_version }}/jre/lib/security/cacerts-{{ dt_suffix.stdout }}"
    remote_src: yes

- name: "Copy cacerts from {{ current_jdk_version }} to {{ jdk_version }}"
  copy:
    src: "/opt/oracle/{{ current_jdk_version }}/jre/lib/security/cacerts"
    dest: "/opt/oracle/{{ jdk_version }}/jre/lib/security/"
    remote_src: yes

- name: Update existing java soft link to use new jdk
  file:
    dest: "/opt/oracle/java"
    src: "/opt/oracle/{{ jdk_version }}"
    state: link
