- name: "Validate if {{ folder }} backup available with {{ dt_formatted }}"
  stat:
    path: "/opt/oracle/{{ folder }}{{ fmw_version }}-{{ dt_formatted }}"
  register: backup_status
  
- debug:
    var: backup_status

#- name: "Backup {{ folder }}"
#  synchronize:
#    src: "/opt/oracle/{{ folder }}{{ fmw_version }}/"
#    dest: "/opt/oracle/{{ folder }}{{ fmw_version }}-{{ dt_formatted }}/"
#    recursive: yes
#    rsync_opts:
#    - "--exclude=*.log*"
#    - "--exclude=*.out*"
#    - "--exclude=*.hprof*"
#    - "--exclude=*erver*/tmp/*"
#    - "--exclude=*erver*/cache/*"
#    - "--exclude=*bsu/cache_dir/*"
#    #- "--ignore-missing-args"
#  delegate_to: "{{ inventory_hostname }}"
#  when: backup_status.stat.exists == false

- name: "Backup {{ folder }}"
  copy:
    src: "/opt/oracle/{{ folder }}{{ fmw_version }}"
    dest: "/opt/oracle/{{ folder }}{{ fmw_version }}-{{ dt_formatted }}"
    remote_src: yes
    directory_mode: yes
  when: backup_status.stat.exists == false
