- name: Pick date
  shell: "date +'%m%d%Y-%H%M%S'"
  register: dt
  run_once: true

- name: Start indefinite blackout
  shell: "ls -F {{ OEM_AGENT_HOME }}/bin/emctl && {{ OEM_AGENT_HOME }}/bin/emctl start blackout maintenance-{{ dt.stdout }}-from-ansible-by-{{ hostvars[inventory_hostname]['awx_user_name'] }} -nodeLevel"
  ignore_errors: true
  when: blackout_duration is undefined

- name: Start limited blackout
  shell: "ls -F {{ OEM_AGENT_HOME }}/bin/emctl && {{ OEM_AGENT_HOME }}/bin/emctl start blackout maintenance-{{ dt.stdout }}-from-ansible-by-{{ hostvars[inventory_hostname]['awx_user_name'] }} -nodeLevel -d {{ blackout_duration }}"
  ignore_errors: true
  when: blackout_duration is defined

#- name: Pause execution for 10 seconds
#  pause:
#    seconds: 10
#  delegate_to: localhost
