- shell: "cat {{ outputFile.path }}"
  register: op

- block:
  - name: Collate results to localhost
    shell: "echo {{ inventory_hostname }}:  {{ item }} >> {{ outputFile.path }}"
    with_items:
    - "{{ op.stdout_lines }}"

  - name: "Validate if {{ outputFile.path }} exists"
    stat: 
      path: "{{ outputFile.path }}"
    register: outputexists
    run_once: true
  delegate_to: localhost

- name: Remove tempfile
  file:
    path: "{{ outputFile.path }}"
    state: absent

- block:
  - name: Pick date
    shell: "date +'%D'"
    register: dt

  - name: Copy collated results from Ansible server to one of the servers
    copy:
      src: "{{ outputFile.path }}"
      dest: /tmp/

  - name: Display results
    shell: "cat {{ outputFile.path }}"
  
  - name: Send results over email
    shell: "cat {{ outputFile.path }} | sort | mail -s GINT-Weblogic-{{ env }}-Health-check-report-{{ dt.stdout }} -r {{ ansible_tower_mail_id }}@`hostname -d` {{ email_ids }} {{ custom_mailids }}"

  - name: Remove tempfile on ansible server
    file:
      path: "{{ outputFile.path }}"
      state: absent
    delegate_to: localhost
  run_once: true
  when: outputexists.stat.exists == true
