- name: Pick date
  shell: "date"
  register: dt

- name: Pick domain name
  shell: "hostname -d"
  register: host_domain

- name: Create scripts folder to place the scripts
  file: 
    path: "{{ scripts_home }}"
    state: directory

- name: Copy scripts to build server
  copy:
    src: "../../../../apps/pm-activate-deactivate-store/{{ item }}"
    dest: "{{ scripts_home }}"
  with_items:
  - "call_MHS_PM_activity.sh"
  - "MHS_PM_activity_OPT.py"
  - "MHS_PM_status_OPT.py"

- name: Copy properties file to remote server
  copy:
    src: "../../../../apps/pm-activate-deactivate-store/MHS_ACT_PM_PARAM.properties"
    dest: "{{ scripts_home }}/.MHS_ACT_PM_PARAM.properties"

- name: Set facts for status
  set_fact:
    email_ids: "{{ hostvars[inventory_hostname]['awx_user_name'] }}@ikea.com"
    script_name: "MHS_PM_status_OPT.py"
    output_file: "MhsStoreStatus.html"
    email_subject: "{{ env_name }}-MHS-store-{{ store_number }}-status-{{ dt.stdout }}"
    schema_list: "null"
  when: activity == "status"

- block:
  - debug: 
      msg: "{{ schemas }}"

  - name: Set facts for activate/deactivate
    set_fact:
      schema_list: "{%- print (schemas|string).replace('[','').replace(']','').replace(' ','').replace('u\\'','').replace('\\'','') -%}"
      email_ids: "{{ activate_deactivate_store_mail_ids }}"
      script_name: "MHS_PM_activity_OPT.py"
      output_file: "PMactivity.html"
      email_subject: "{{ env_name }}-MHS-store-{{ store_number }}-{{ activity }}-status-{{ dt.stdout }}"

  - debug: 
      msg: "{{ schema_list }}"
  when: activity != "status"

- name: Run the script
  shell: "cd {{ scripts_home }} && sh call_MHS_PM_activity.sh {{ store_number }} {{ activity }} {{ env_name }} {{ scripts_home }} {{ script_name }} {{ [schema_list] | to_yaml }}"
  register: op

#- name: Send results over email
#  shell: |
#          (echo -e 'Subject: {{ env_name }}-MHS-store-{{ store_number }}-{{ activity }}-status-{{ dt.stdout }}\nFrom: {{ ansible_tower_mail_id }}@ikeadt.com\nTo: {{ activate_deactivate_store_mail_ids }}\nContent-Type: text/html\n\n';cat {{ scripts_home }}/PMactivity.html) | /sbin/sendmail -f {{ ansible_tower_mail_id }}@ikeadt.com {{ activate_deactivate_store_mail_ids }}
- name: Send results over email
  shell: |
          (echo -e 'Subject: {{ email_subject }} \nFrom: {{ ansible_tower_mail_id }}@{{ host_domain.stdout }}\nTo: {{ email_ids }}\nContent-Type: text/html\n\n';cat {{ scripts_home }}/{{ output_file }}) | /sbin/sendmail -f {{ ansible_tower_mail_id }}@{{ host_domain.stdout }} {{ email_ids }} 

