- name: Create tempfile
  tempfile:
    state: file
    path: /tmp
    prefix: appd-key-verify
  register: outputFile
  run_once: true
  delegate_to: ptseelm-lx4253.ikeadt.com

- name: Create scripts directory to place scripts
  file:
    path: "/opt/oracle/scripts"
    state: "{{ item }}"
  with_items:
  - "absent"
  - "directory"

- name: Copy verification script
  copy:
    src: "../../../../shell-scripts/appdkeyverify.sh"
    dest: /opt/oracle/scripts

- name: Execute verification script
  shell: "sh /opt/oracle/scripts/appdkeyverify.sh {{ vars[env + '_old_key'] }} {{ vars[env + '_new_key'] }}"
  register: output

- name: Accumulate output from all hosts to localhost
  shell: |
          echo "{{ output.stdout }}" >> {{ outputFile.path }}
  delegate_to: ptseelm-lx4253.ikeadt.com

- block:
  #- name: Copy collated results from Ansible server to one of the servers
  #  copy:
  #    src: "{{ outputFile.path }}"
  #    dest: /tmp/
  - name: Display results
    shell: "cat {{ outputFile.path }}"
    delegate_to: ptseelm-lx4253.ikeadt.com
    register: results

  - name: Send results over email
    shell: |
            echo "{{ results.stdout }}" | sort | mail -s {{ env }}-GINT-Weblogic-appd-key-verification-report -r {{ ansible_tower_mail_id }}@`hostname -d` {{ email_ids }}

  - name: Remove tempfile
    file:
      path: "{{ outputFile.path }}"
      state: absent
    delegate_to: "{{ item }}"
    with_items:
    - "{{ inventory_hostname }}"
    - "ptseelm-lx4253.ikeadt.com"
  run_once: true
