- name: Create tempfile
  tempfile:
    state: file
    path: /tmp
    prefix: cds-migration-report
  register: outputFile
  run_once: true

- name: Extract cds server from config.xml
  shell: |
          cat /opt/oracle/domains{{ fmw_version }}/{{ item }}/config/config.xml | grep 'cds' | sed 's/wls:host//g' | sed 's/\///g' | sed 's/<>//g' | sed 's/ //g' | uniq | paste -s -d, - | grep -v 'cdsp' >> {{ outputFile.path }}
  with_items:
  - "{{ domains.split(',') }}"

- name: "Change permissions of {{ outputFile.path }}"
  file: 
    path: "{{ outputFile.path }}"
    state: file
    mode: 0777
