email_ids: 'nagarjuna.palagiri@ingka.com thiyagu.c@ingka.com surendranadh.swamy.nathan@ingka.com jeelanibasha.syed@ingka.com rajesh.jayavelu@ingka.com narayanaswamy.perimala@ingka.com sudheer.tripurari@ingka.com vijayakumar.seetha@ingka.com chenchuratnam.rapuru@ingka.com dhanunjaya.chenna@ingka.com vignesh.radhakrishnan@ingka.com sureshkrishnan.goverdhanan@ingka.com dineshkumar.l@ingka.com rajesh.n@ingka.com kandasamy.ayyapillai@ingka.com santoshkumar.singh1@ingka.com vivekkumar.bansal@ingka.com'
test_email_ids: 'praveen.kandregula@ingka.com'
ansible_tower_mail_id: 'ansible-tower'
OEM_AGENT_HOME: '/u01/oracleagent/agent_inst'
confidential_email_ids: 'thiyagu.c@ingka.com surendranadh.swamy.nathan@ingka.com prakash.natanasabapathi@ingka.com'
team_mail_id: 'dl.gint.infra.se@ingka.com'
activate_deactivate_store_mail_ids: 'sandeep.kumar1@ingka.com,richa.garg@ingka.com,neelotpal.pandey@ingka.com,syed.jaweed@ingka.com,prakash.natanasabapathi@ingka.com,upasana.maurya1@ingka.com,kamal.gupta@ingka.com,shiv.kumar@ingka.com,ankit.saini@ingka.com,asit.bhushan@ingka.com'
wallet_entry_email_ids: 'prakash.natanasabapathi@ingka.com thiyagu.c@ingka.com surendranadh.swamy.nathan@ingka.com sandeep.kumar1@ingka.com richa.garg@ingka.com syed.jaweed@ingka.com upasana.maurya1@ingka.com kamal.gupta@ingka.com shiv.kumar@ingka.com ankit.saini@ingka.com asit.bhushan@ingka.com neelotpal.pandey@ingka.com'
scripts_home: '/opt/oracle/scripts'

#BAM
DEV_bam_url: 't3://ptseelm-lx4720.ikeadt.com:8001,ptseelm-lx4721.ikeadt.com:8001'
PTE_bam_url: 't3://ptseelm-lx4720.ikeadt.com:8001,ptseelm-lx4721.ikeadt.com:8001'
CTE_bam_url: 't3://cfseelm-lx4378.ikeadt.com:8001,cfseelm-lx4379.ikeadt.com:8001'
PPE_bam_url: 't3://bamowd1207m01.ikeadt.com:8001,bamowd1207m02.ikeadt.com:8001,bamowd1207m03.ikeadt.com:8001,bamowd1207m04.ikeadt.com:8001'
PROD_bam_url: 't3://bamowd1268m01.ikea.com:8001,bamowd1268m02.ikea.com:8001,bamowd1268m03.ikea.com:8001,bamowd1268m04.ikea.com:8001'

#APPD
PPE_old_key: '6cvs4iglty4t' 
PPE_new_key: '5b27fe7d-7e9f-4b65-bf5d-111e74ec951c'
#PPE_version: '4.5.4.24355'
PPE_version: '4.5.18.29239'
PPE_controller_host: 'ikeadev.saas.appdynamics.com'
PPE_controller_port: '443'
PPE_controller_account: 'ikeadev'
PROD_old_key: 'wrxw8gfyoesx'
PROD_new_key: 'b527515b-69d0-4627-870d-525a4aab6026'
PROD_version: '4.5.18.29239'
PROD_controller_host: 'ikeaprod.saas.appdynamics.com'
PROD_controller_port: '443'
PROD_controller_account: 'ikeaprod'

#JENKINS
PTE_jenkins: 'pte-iiptools.ikeadt.com'
CTE_jenkins: 'pte-iiptools.ikeadt.com'
PPE_jenkins: ''
PROD_jenkins: ''
jenkins_gint_infra_recepients: 'praveen.kandregula@ingka.com;nagarjuna.palagiri@ingka.com;thiyagu.c@ingka.com;surendranadh.swamy.nathan@ingka.com;jeelanibasha.syed@ingka.com;rajesh.jayavelu@ingka.com;narayanaswamy.perimala@ingka.com;sudheer.tripurari@ingka.com;vijayakumar.seetha@ingka.com;chenchuratnam.rapuru@ingka.com;dhanunjaya.chenna@ingka.com;vignesh.radhakrishnan@ingka.com;prakash.natanasabapathi@ingka.com;sureshkrishnan.goverdhanan@ingka.com;dineshkumar.l@ingka.com;rajesh.n@ingka.com;kandasamy.ayyapillai@ingka.com;santoshkumar.singh1@ingka.com;vivekkumar.bansal@ingka.com'