- name: Extract AdminPort
  shell: |
          awk '/AdminChannel/ {p=1}; p; /<\/network-access-point>/ {p=0}' /opt/oracle/domains{{ fmw_version }}/{{ domain_name }}/config/config.xml | grep 'listen-port' | sed 's/listen-port//g' | sed 's/<//g' | sed 's/>//g' | sed 's/\///g' | sed 's/ //g'
  register: adminport

- name: Extract AdminHost
  shell: |
          awk '/AdminChannel/ {p=1}; p; /<\/network-access-point>/ {p=0}' /opt/oracle/domains{{ fmw_version }}/{{ domain_name }}/config/config.xml | grep 'listen-address' | sed 's/listen-address//g' | sed 's/<//g' | sed 's/>//g' | sed 's/\///g' | sed 's/ //g'
  register: adminhost

- set_fact:
    admhost: "{{ adminhost.stdout }}"
    admport: "{{ adminport.stdout }}"
