- name: Create tempfile to store output
  tempfile:
    state: file
    path: /tmp
    prefix: backup-dump-purge-output
  register: outputFile
  run_once: true

- set_fact: 
    ansiblePath: "{{ outputFile.path }}"

- name: Get usage stats
  shell: "if [[ $(df -Ph | grep '{{ item }}$' | awk '{print $5}' | cut -d'%' -f1) -gt 75 ]]; then echo $(df -Ph | grep '{{ item }}' | awk '{print $6 \" - \" $5}') >> {{ ansiblePath }}; fi"
  with_items:
  - "/opt"
  - "/u01"
  - "/u01/app/oracle"

- name: Print results
  shell: "cat {{ ansiblePath }}"

- name: Remove tempfile
  file:
    path: "{{ ansiblePath }}"
    state: absent
